config/routes.rb
Rails.application.routes.draw do

  get 'scoutentry/index'

  resources :bluecards

  root 'application#index'

  devise_for :users
  resources :line_items

  resources :carts

  resources :products

  get 'index/index'

  get 'application/index'

  get 'bluecards/new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_midlanding.html.erb
<div class="row">
  <div class="large-4 columns">
     <div class="panel">
       <h5 class="subheader"><%= link_to 'Create Blue Cards', bluecards_new_path, :class => 'button' %></h5>
     </div>
  </div>

  <div class="large-4 small-6 columns">
    <!-- 300 x 465 -->
    <%= image_tag("TroopTrackAd.png", :alt => "Image Error") %>
  </div>

  <div class="large-4 columns">
   <div class="panel">
     <h3>Test</h3>
      Test Test
   </div>
 </div>
</div>

app/views/application/_stufftodo.html.erb
<% if user_signed_in? %>

<div class="row">
  <div class="large-12 columns">
    <div class="row">

      <div class="large-4 small-6 columns">

        <h4>Stuff To Do</h4><hr>

        <div class="row">
          <div class="large-1 column">
            <img src="http://placehold.it/50x50&text=[img]">
          </div>

          <div class="large-9 columns">
            <h5><a href="#" class="button">Create Scouts</a></h5>
            <h6 class="subheader show-for-small">Subheader</h6>
          </div>
        </div><hr>

        <div class="hide-for-small">
          <div class="row">
            <div class="large-1 column">
              <img src="http://placehold.it/50x50&text=[img]">
            </div>

            <div class="large-9 columns">
              <h5 class="subheader"><%= link_to 'Create Blue Cards', bluecards_new_path, :class => 'button' %></h5>
            </div>
          </div><hr>

          <div class="row">
            <div class="large-1 column">
              <img src="http://placehold.it/50x50&text=[img]">
            </div>

            <div class="large-9 columns">
              <h5 class="subheader"><a href="#" class="button">Print BlueCards</a></h5>
            </div>
          </div><hr>

          <div class="row">
            <div class="large-1 column">
              <img src="http://placehold.it/50x50&text=[img]">
            </div>

            <div class="large-9 columns">
              <h5 class="subheader"><a href="#" class="button">View Orders</a></h5>
            </div>
          </div>
        </div>
      </div>

      <% else %>

      <div class="row">
        <div class="large-12 columns">
          <div class="row">

            <div class="large-4 small-6 columns">

              <h4>Stuff To Do</h4><hr>

              <div class="row">
                <div class="large-1 column">
                  <img src="http://placehold.it/50x50&text=[img]">
                </div>

                <div class="large-9 columns">
                  <h5><a href="#" class="button disabled">Create Scouts</a></h5>
                  <h6 class="subheader show-for-small">Subheader</h6>
                </div>
              </div><hr>

              <div class="hide-for-small">
                <div class="row">
                  <div class="large-1 column">
                    <img src="http://placehold.it/50x50&text=[img]">
                  </div>

                  <div class="large-9 columns">
                    <h5 class="subheader"><a href="#" class="button disabled">Create BlueCards</a></h5>
                  </div>
                </div><hr>

                <div class="row">
                  <div class="large-1 column">
                    <img src="http://placehold.it/50x50&text=[img]">
                  </div>

                  <div class="large-9 columns">
                    <h5 class="subheader"><a href="#" class="button disabled">Print BlueCards</a></h5>
                  </div>
                </div><hr>

                <div class="row">
                  <div class="large-1 column">
                    <img src="http://placehold.it/50x50&text=[img]">
                  </div>

                  <div class="large-9 columns">
                    <h5 class="subheader"><a href="#" class="button disabled">View Orders</a></h5>
                  </div>
                </div>
              </div>
            </div>
<% end %>

app/views/application/index.html.erb
<div class="row">
 <div class="large-12 columns">

   <div class="row">
     <div class="large-12 hide-for-small">

       <div id="featured" data-orbit>

<!---1200 x 500 -->
         <%= image_tag("rsz_1banner.png", :alt => "Image Error") %>

         </div>

   </div>
 </div>

   <div class="row">
     <div class="large-12 columns show-for-small">

<!---1200 x 700 -->
       <%= image_tag("banner.png", :alt => "Image Error") %>

     </div>
   </div><br>

<%= render "midlanding" %>


<div class="row">
     <div class="large-12 columns"><hr>
         <div class="row">
           <div class="large-6 columns">
               <p>Copyright Stuff</p>
           </div>

           <div class="large-6 small-12 columns">
               <ul class="inline-list right">
                 <li><a href="#">Link 1</a></li>
                 <li><a href="#">Link 2</a></li>
                 <li><a href="#">Link 3</a></li>
                 <li><a href="#">Link 4</a></li>
               </ul>
           </div>

         </div>
     </div>
   </footer>

 </div>
</div>